---

- name: "Collect potential host-file"
  ansible.builtin.stat:
    path: "{{ host_files_dir.stat.path + '/' + (file.path.split(project_name + '/')[1:] | join(project_name + '/')).split('.j2')[0] }}"
  delegate_to: "localhost"
  when: file_type != 'host_file' and host_files_dir.stat.isdir is defined and host_files_dir.stat.isdir
  register: potential_host_file

- name: "Define remote path"
  ansible.builtin.set_fact:
    remote_path: "{{ project_dir + '/' + (file.path.split(project_name + '/')[1:] | join(project_name + '/')).split('.j2')[0] }}"

- name: "Set effective owner for file"
  ansible.builtin.set_fact:
    project_deployment_file_owner: "{{ project_deployment_file_owner_overrides[file.path | basename].owner | default(project_deployment_owner) }}"
    project_deployment_file_group: "{{ project_deployment_file_owner_overrides[file.path | basename].group | default(project_deployment_group) }}"

- name: "Copy file if no host_file exists or copy host_file"
  ansible.builtin.copy:
    src: "{{ file.path }}"
    dest: "{{ remote_path }}"
    mode: "{{ project_deployment_file_mode if not \
      remote_path | ifalatik.docker.any_regex_matches(regex_secret_remote_paths) \
      else project_deployment_secret_file_mode }}"
    owner: "{{ project_deployment_file_owner }}"
    group: "{{ project_deployment_file_group }}"
  become: true
  diff: "{{ not remote_path | ifalatik.docker.any_regex_matches(regex_secret_remote_paths) }}"
  when: file_type == 'host_file' or
    ( file_type == 'file' and not ( potential_host_file.stat.exists is defined and potential_host_file.stat.exists ) )
  register: copy_result
  
- name: "Copy template if no host_file exists"
  ansible.builtin.template:
    src: "{{ file.path }}"
    dest: "{{ remote_path }}"
    mode: "{{ docker_file_mode if not \
      remote_path | any_regex_matches(regex_secret_remote_paths) \
      else docker_secret_file_mode }}"
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
  diff: "{{ not remote_path | any_regex_matches(regex_secret_remote_paths) }}"
  when: file_type == 'template' and not ( potential_host_file.stat.exists is defined and potential_host_file.stat.exists )
  notify: ["Restart project"]

...
